---
title: "About"
toc: true
toc-location: left
preview: images/photo.jpg
lightbox: true
execute: 
  echo: false
  warning: false
---

```{r setup}
source("_common.R")
```

Welcome! I am a researcher, economist, data geek, baker, dog mom, and Assistant Professor at Colorado State University. I study food retail markets, consumer food decisions, and food prices. Through projects like [DemocratizingData.ai](https://democratizingdata.ai/), I work to make information more transparent, equitable, and build to serve the public good. See my [CV](cv.qmd) for more details.

# Short Bio

John Paul (JP) is an Assistant Professor at George Washington University in the Department of Engineering Management and Systems Engineering. His [research](research.qmd) focuses on understanding how consumer preferences, market dynamics, and policy affect the emergence and adoption of low-carbon technologies, such as electric vehicles and renewable energy technologies. He also studies the critical relationship between the US and China in developing and mass producing these technologies. He has expertise in discrete choice modeling, conjoint analysis, survey design, exploratory data analysis, interview-based research methods, the R programming language, China, and the global electric vehicle industry. He speaks fluent Mandarin Chinese and has conducted extensive fieldwork in China. John holds a Ph.D. and M.S. in Engineering and Public Policy from Carnegie Mellon University and a B.S. in Engineering Science and Mechanics (ESM) from Virginia Tech.

-----

## Looking for a speaker, advisor, or collaborator? Let’s talk.

<iframe 
  src="https://hz1r899b.forms.app/lets-get-touch"
  width="100%" 
  height="600" 
  frameborder="0" 
  style="border: none;">
</iframe>

<!-- https://forms.app/myforms -->
