---
title: "Slides"
execute: 
  echo: false
  warning: false
format: 
  html:
    page-layout: full
---

```{r setup}
source("_common.R")
```

General introduction to my current research: [HTML](https://slides.jhelvy.com/helveston-research), [PDF](https://github.com/jhelvy/slides/raw/main/helveston-research/helveston-research.pdf)

Slides for various talks:

```{r, echo=FALSE}

# NOTE: The slides.lua file is inserted as a filter in _quarto.yml to 
# avoid the insertion of a <colgroup> in the html around this table: 
# https://github.com/jgm/pandoc/issues/8139

library(knitr)
library(dplyr)
library(kableExtra)
library(glue)
library(tinytable)

slides <- readr::read_csv(file.path('content', 'slides.csv')) %>%
    mutate(
        slides = glue('[HTML](https://jhelvy.github.io/{repo})'),
        pdf = glue('[PDF](https://github.com/jhelvy/{repo}/blob/main/{repo}.pdf?raw=true)')
    ) %>%
    select(-repo) %>%
    janitor::clean_names(case = 'title') %>%
    rename(" " = Pdf)

slides |> 
  tt(theme = "grid", width = c(0.3, 0.8, 0.8, 0.5, 0.1, 0.1)) |>
  style_tt(fontsize = 1) |> 
  format_tt(quarto = TRUE)
```
