---
title: "Teaching"
description: I teach undergraduate and graduate courses in the [Department of Agricultural and Resource Economics](https://agsci.colostate.edu/dare/) at Colorado State University.
preview: images/lab/john_helveston.png
toc: true
toc-location: left
toc-title: "Courses"
execute: 
  echo: false
  warning: false
---

```{r setup}
source("_common.R")
```

<center>
Content for **workshops** I've given can be found at [laurenchenarides.com/workshops](workshops.qmd)
</center>

### [AREC 224/280A-1: Introduction to Agribusiness Entrepreneurship](https://laurenchenarides.github.io/csu-arec-224/)

::: {.grid}

::: {.g-col-9}

This course introduces students to the fundamentals of entrepreneurship. It is designed for students interested in developing problem-solving skills, business acumen, and–most notably–an entrepreneurial mindset. The course emphasizes how individuals identify opportunities, develop business models, and create ventures that address challenges in agriculture and food systems.

:::

::: {.g-col-3}

**Semesters Taught**:

- [Fall 2025](https://laurenchenarides.github.io/csu-arec-224/)
- Fall 2024

:::

:::

### [AREC 310: Food and Agricultural Markets](https://laurenchenarides.github.io/csu-arec-310/)

::: {.grid}

::: {.g-col-9}

The primary objective is to foster development and understanding of key agricultural marketing issues and concerns, equip you with analytical skills that may be utilized to evaluate different marketing problems and programs from both the industry and firm perspective. This course will provide you with an understanding of economic concepts that will be employed for analyzing issues in agricultural marketing

:::

::: {.g-col-3}

**Semesters Taught**:

- [Fall 2025](https://laurenchenarides.github.io/csu-arec-310/)
- Fall 2024

:::

:::

### [AREC 330: Data-Driven Decision Making n Agricultural and Resource Economics](https://csu-arec-330.github.io/)

::: {.grid}

::: {.g-col-9}

The world generates 2.5 quintillion bytes of data each day. One of the key modern business challenges is transforming that data into actionable insights that improve decision making (i.e., data-driven decision making). Transforming data into information is not magic. It requires understanding the decision problem, organizing and processing data, analyzing data, and finally presenting information. This course will introduce you to this process of transforming data into actionable insights and build a core set of competencies with two commonly used software: R and Tableau. Since we only have 16 weeks, the most important lesson you will learn in this class is how to teach yourself what you need to know in the future. You will learn these skills by completing the three group projects over the semester.

:::

::: {.g-col-3}

**Semesters Taught**:

- [Spring 2025](https://csu-arec-330.github.io/)
- [Spring 2024](https://csu-arec-330.github.io/)

:::

:::

### [AREC 570: Methodology of Economic Research](https://catalog.colostate.edu/general-catalog/courses-az/arec/)

::: {.grid}

::: {.g-col-9}

Philosophical foundations of science and research. Concepts and skills for planning, performing, reporting, and evaluating economic research.

:::

::: {.g-col-3}

**Semesters Taught**:

- Fall 2026 (*Coming Soon*)

:::

:::
